### ISSUE TITLE
OpenAPI documentation

### ISSUE THREAD

**Issue by cobraz** [PowerOffice/go-api#10]
Hello!

I am working on integrations between PowerOffice Go and other software. After looking around, I couldn't find any clients for any of the languages I write in, but I found an OpenAPI specification while looking. After opening an issue there (spysystem/poweroffice-go#1), I created a repository that only holds a fork of the OpenAPI spec (with the intentions of further adding to it) that `spysystem` had created.

Before we continue to create and maintain our own OpenAPI spec, I want to verify that you don't have an official spec that can be shared?

**Our repository:**
https://github.com/bjerkio/poweroffice-go-openapi

If not, help would be highly appreciated!

**Comment by rodfjell** [comment]
Hi,

We do not provide an OpenAPI specification currently due to the fact that some of our services deviate from the standard. We are however working on modernizing the API, and will at a later date release a second version of the API. This second version will provide an OpenAPI specification.

**Comment by cobraz** [comment]
Thank you for the reply, @rodfjell!

Do you have an ETA on that? I'd love to be able to evaluate whether I should start the next implementation now, or wait until the API is available.
