### ISSUE TITLE
Issue in Customer service

### ISSUE THREAD

**Issue by asamofal** [PowerOffice/go-api#13]
Hello! There's an issue in "Customer" service.

Documentation says:
> All input and response data is transferred using the [JSON format](http://www.json.org/). Response data is always wrapped in an object with a success boolean property and a data property containing the actual object returned by the api call.

But in case of POST request to https://api.poweroffice.net/Customer endpoint (to create a new customer) with just a few fields: 
```json
{"FirstName":"Anton","LastName":"Samofal","Email":"soresunnmore@lokal.naf.n0","isPerson":"true"}
```
we are getting just **empty response**. It's because of invalid email (zero at the end of the string). Seems like you have an issue in email validation - as I've mentioned previously, only responses in JSON are expected all over the API.

It would be nice if this issue were fixed :)

**Comment by kridah** [comment]
Hi,

"Email" is not a valid property in the Customer object. Did you mean "emailAddress"? Using emailAddress and "soresunnmore@lokal.naf.n0" will throw an exception.

**Comment by asamofal** [comment]
> Hi,
> 
> "Email" is not a valid property in the Customer object. Did you mean "emailAddress"? Using emailAddress and "soresunnmore@lokal.naf.n0" will throw an exception.

Yes, it's just mistake in my example above. I had use  `emailAddress` in Customer object, the response was empty in that case,

**Comment by kridah** [comment]
A request with the follow input:

`{
    "FirstName": "Anton",
    "LastName": "Samofal",
    "emailAddress": "soresunnmore@lokal.naf.n0",
    "isPerson": "true"
}`

will return the following response:

`{
    "success": false,
    "validation": {
        "errorLogReference": "1gnk4v33vji-0126084730",
        "summary": "Invalid email address soresunnmore@lokal.naf.n0",
        "exception": "AggregatedValidation",
        "fields": {
            "email": {
                "__message": "Invalid email address soresunnmore@lokal.naf.n0"
            }
        }
    }
}`
