### ISSUE TITLE
REST: /Reporting/AccountTransactions/{accountCode} returning 404

### ISSUE THREAD

**Issue by NateNjuguna** [PowerOffice/go-api#15]
Hi Testing this route with valid authorization returns 404 for any valid accountCode(s) i.e.
```
GET /Reporting/AccountTransactions/1500?fromDate=2021-01-01&toDate=2021-02-01 HTTP/1.1
Host: api-demo.poweroffice.net
Authorization: Bearer <token>
```
Returns

> < HTTP/1.1 404 The controller for path '/Reporting/AccountTransactions/1500' was not found or does not implement IController.
< Cache-Control: private
< Request-Context: appId=<app ID>
< Access-Control-Expose-Headers: Request-Context
< X-Cache: CONFIG_NOCACHE
< X-Azure-Ref: <ref>
< Date: Mon, 04 Apr 2022 07:02:43 GMT
< Content-Length: 0
< 
< * Connection #0 to host api-demo.poweroffice.net left intact

**Comment by kridah** [comment]
Hi,

The documentation is wrong. Provide accountCode as a parameter. 
`GET /Reporting/AccountTransactions/?accountCode=1500&fromDate=2021-01-01&toDate=2021-02-01`

**Comment by NateNjuguna** [comment]
> Hi,
> 
> The documentation is wrong. Provide accountCode as a parameter. `GET /Reporting/AccountTransactions/?accountCode=1500&fromDate=2021-01-01&toDate=2021-02-01`

Hi @kridah I tried the query above and I get results similar to the following query so I believe this is correct and the documentation should be updated

`GET /Reporting/AccountTransactions?fromDate=2021-01-01&toDate=2021-02-01&$filter=(AccountCode eq 2940)`

> {
    "data": [ ... ],
    "success": true,
    "count": xx
}

**Comment by kridah** [comment]
Both variations are valid.
`/Reporting/AccountTransactions/?$filter=(AccountCode eq 1500)&fromDate=2022-01-01&toDate=2023-02-01`
`/Reporting/AccountTransactions/?fromDate=2022-01-01&toDate=2023-02-01&accountCode=1500`
