### ISSUE TITLE
Invoice lines have changed order

### ISSUE THREAD

**Issue by clevrdavid** [PowerOffice/go-api#29]
Hi, has there been a recent change to how Outgoing Invoice Lines are ordered?

We previously had a description line (LineType.Text) added under each invoice line (LineType.Normal) to provide more reference for what the line above related to. 

Now it seems all these text lines (without product numbers) are collected below all the normal lines that contain product numbers and amounts. This is actually a major issue for customers to reconcile each charge.

**Comment by kridah** [comment]
I will look into it and report back.

**Comment by clevrdavid** [comment]
Thanks @kridah, any updates? Would like to understand how the sorting now works as we need to fix this urgently (end of month tomorrow).

**Comment by clevrdavid** [comment]
It looks like this can be overrided using the SortOrder property for each invoice line.
