### ISSUE TITLE
Evaluation timed out while reading OutgoingInvoice

### ISSUE THREAD

**Issue by subashdbc** [PowerOffice/go-api#3]
Hi,
I use a demo account to sync Customers and Invoices with PowerOffice. Customers are working OK.
But while reading all the `OutgoingInvoice` ([sample code from here](https://github.com/PowerOffice/go-api/blob/master/Examples/OutgoingInvoice/Program.cs)), 
it throws issue like this.

> Error = The metadata for 'GoApi' is invalid. If you are debugging a minidump, you may be able to fix this problem by collecting a new minidump with heap and evaluating the expression again.

How to fix this? 
Thanks in advance!

**Comment by rodfjell** [comment]
This seems unrelated to the GoApi nuget package. Not familiar with the error you're getting, but it seems like the debugger is the one throwing the exception. The only thing I can find related to this error is invalid conditional breakpoints.

If you're using the demo code we've provided on GitHub, the only type of exceptions I can think of that you can be getting are security exceptions - either related to incorrect ApplicationKey / ClientKey or EndPointHost or that our settings for your integration has not given access to the OutgoingInvoice service. We can on our end control the access on each of the services in the API - so the integration might be set up with access to Customers, but not OutgoingInvoice.

I would suggest sending our API support team an e-mail where you provide the name of the integration and the demo client name so we can check up how the integration is set up. You can reach our API support team on: go-api@poweroffice.no

**Comment by subashdbc** [comment]
Thanks for your response, we will reach out to support team
