### ISSUE TITLE
Callback hooks avaliable?

### ISSUE THREAD

**Issue by subashdbc** [PowerOffice/go-api#4]
Hi,
Just a question
Is there any webhooks methods are available when creating, deleting, editing `customer` and other modules In PowerOffice?

**Comment by rodfjell** [comment]
Hi,

We don't have any webhook methods available in the API. Integrations that needs to keep track on changes on Customers usually do this by querying the Get method filtering by LastChanged.

**Comment by subashdbc** [comment]
Ok Thanks

**Comment by BobbyTable** [comment]
@rodfjell  Is this still the case? We were hoping to keep a large set of customers in sync with your data regardless of what system made the change. Wold it be acceptable to poll in intervals?

**Comment by kridah** [comment]
@BobbyTable Unfortunately we still do not support webhooks. Polling is the common way integrations keep their data in sync. We recommend you use the LastChanged property in queries to track changes.

/Kristoffer

**Comment by ai-einar** [comment]
@rodfjell Is there any plans to support webhooks?

**Comment by kridah** [comment]
This version of our API will not support webhooks as it is in maintenance mode.
It's a feature we know developers want, and it is on our roadmapped as a planned feature, but at this time we cannot give an estimate for when it will be available for our new API ([link to developer portal](https://developer.poweroffice.net)).
