### ISSUE TITLE
$skip query param returns "NotSupported"

### ISSUE THREAD

**Issue by ChristopherKrohn** [PowerOffice/go-api#6]
I perform a query with the $skip param:

GET https://api.poweroffice.net/customer?$skip=1 HTTP/1.1

**Expected result:**
Response does not contain the first record in the result set.

**Actual result:**
{
    "success": false,
    "validation": {
        "errorLogReference": "riw0lyxpupt-0429070434",
        "summary": "",
        "exception": "NotSupported"
    }
}

**Comment by rodfjell** [comment]
Hi,

Our OData queries are not ordered by default, so when using $skip the query must also include an $orderby option. In other words the query needs to include something like this: `$skip=1&orderby=Code`

More information about Query String Options can be foiund here:
https://www.odata.org/documentation/odata-version-2-0/uri-conventions/

**Comment by ChristopherKrohn** [comment]
Great, that solved it. 
Thanks.

It might just be a lack of knowhow from me, but it could be smart to add this to the API-documentation.
