### ISSUE TITLE
Pagination params don't work as expected for TeamMembers route.

### ISSUE THREAD

**Issue by volodymyr-sevastianov** [PowerOffice/go-api#7]
If we specify `$skip` and `$top` then API responses with `501 Not Implemented`. I've tried it in another way (without dollar sign '$') `skip` and `top` and everything worked correctly.

**Comment by rodfjell** [comment]
@volodymyr-sevastianov Both $skip and $top should be working. Tried using it now, and I got the expected result with this request against our demo environment:
`https://api-demo.poweroffice.net/customer/?$orderby=Code&$top=5&$skip=5`

Is there any particular service you're reciving the 501 error on?

**Comment by volodymyr-sevastianov** [comment]
Yes, I'm talking about TeamMembers service : `https://api-demo.poweroffice.net/project/:id/teammember`.

**Comment by volodymyr-sevastianov** [comment]
I've found today that service TimeTracking/Activities has the same behavior as TeamMembers.

**Comment by bojan-kukricar** [comment]
> @volodymyr-sevastianov Both $skip and $top should be working. Tried using it now, and I got the expected result with this request against our demo environment:
> `https://api-demo.poweroffice.net/customer/?$orderby=Code&$top=5&$skip=5`
> 
> Is there any particular service you're reciving the 501 error on?

I had the same issue when I was using $skip and $top without $orderby but with $orderby it works. 
Maybe if someone have the same issue it is good to know that it can be solved by using $orderby. 
@rodfjell maybe it will be good to add a default $orderby by Code or Id for customer if $orderby is not specified in the request?
Also here in the examples it can be added one example with "skip" > 0.
