### ISSUE TITLE
EntityCommandExecution exception

### ISSUE THREAD

**Issue by rjkey** [PowerOffice/go-api#8]
GET https://api.poweroffice.net/Reporting/AccountTransactions/

Params: { 
"fromDate": "2020-01-01", 
"toDate": "2020-09-30", 
"$top": 100000, 
"$skip": 0,
"$orderby": "Date" 
}

count > 1000000

Expected result:
Status 200 with valid transaction data

Actual result:
Status 500 with exception message:
{
"success":false,
"validation":{
      "errorLogReference":"cv52njmi4dy-1006140315",
      "summary":"",
      "exception":"EntityCommandExecution"
      }
}

**Comment by rodfjell** [comment]
You are experiencing a database timeout on the request. I would suggest that you reduce the page size on the request ($top) to something like 10.000-20.000.

**Comment by rjkey** [comment]
I tried reducing the page size to 10000. Resultet in same type of exception: 
{"success":false,"validation":{"errorLogReference":"4ruaqx4xdtm-1007105010","summary":"","exception":"EntityCommandExecution"}}
