### ISSUE TITLE
"BinaryFormatter serialization and deserialization are disabled within this application" error

### ISSUE THREAD

**Issue by atlemagnussen** [PowerOffice/go-api#9]
Errormessage when I run
```csharp
authorizationSettings = new AuthorizationSettings
{
    ApplicationKey = applicationKey,
    ClientKey = clientKey,
    TokenStore = new BasicTokenStore("my.tokenstore"),
    EndPointHost = EndPointMode.Demo
};
var api = await Go.CreateAsync(authorizationSettings);
```
inside a aspnet core web app

`BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.`

I believe it's the BasicTokenStore causing this

**Comment by rodfjell** [comment]
@atlemagnussen You're corrrect. It seems like .NET 5.0 prohibits the use of BinaryFormatter that is used in the BasicTokenStore, see https://docs.microsoft.com/en-us/dotnet/core/compatibility/5.0. I will look into rewriting the BasicTokenStore for the next release to move away from BinaryFormatter.

BasicTokenStore is not required for testing/working on the API. You can create your own token store by implementing ITokenStore. This interface only has two methods that requires implementation, GetToken() and SaveToken(). 

Very simple implementation using a dictionary (alter it in any way you like):
```csharp
using System.Collections.Generic;
using GoApi.Core;
​
namespace ApiTesting
{
    public class InMemoryTokenStore : ITokenStore
    {
        protected Dictionary<string, Token> Tokens = new Dictionary<string, Token>();
​
        public Token GetToken(string clientKey)
        {
            Token token;
            lock (this.Tokens)
            {
                this.Tokens.TryGetValue(clientKey, out token);
            }
​
            return token;
        }
​
        public void SaveToken(string clientKey, Token token)
        {
            lock (this.Tokens)
            {
                this.Tokens.Remove(clientKey);
                this.Tokens.Add(clientKey, token);
            }
        }
    }
}
```

Then you use it like this:
```csharp
authorizationSettings = new AuthorizationSettings
{
    ApplicationKey = applicationKey,
    ClientKey = clientKey,
    TokenStore = new InMemoryTokenStore(),
    EndPointHost = EndPointMode.Demo
};
var api = await Go.CreateAsync(authorizationSettings);
```

**Comment by atlemagnussen** [comment]
@rodfjell Thanks! implementing ITokenStore works like a charm 😊

**Comment by rodfjell** [comment]
Version 2.20 of the Nuget package marked BasicTokenStore as obsolete, and provides a BasicInMemoryTokenStore as an alternative. The examples here on github are updated with the new implementation.

Closing this issue.
